# Generated by Django 2.1.7 on 2019-03-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_address',
            field=models.BooleanField(default=True),
        ),
    ]
