# Generated by Django 2.1.7 on 2019-03-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
